---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-mysql
  namespace: logging
data:
  database: spring_boot_db
  user: test

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: logging
spec:
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-mysql
  namespace: logging
data:
  password: dGVzdA==
  root_password: dGVzdA==
type: Opaque

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: user
                  name: configmap-mysql
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: database
                  name: configmap-mysql
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: secret-mysql
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: secret-mysql
          image: mysql
          name: mysql
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
