apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-deployment
  namespace: logging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
        - env:
            - name: SERVICE_B_URL
              valueFrom:
                configMapKeyRef:
                  key: service-b-url
                  name: configmap-apps
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: server-port-app-a
                  name: configmap-apps
          image: dvago88/service_a:latest
          imagePullPolicy: Always
          name: api-service
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: app-a-service
  namespace: logging
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: app-a
  type: LoadBalancer
