apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-cluster-role
  namespace: logging
roles:
  - apiGroups: [""]
    resources: ["pods","namespaces"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["pods/logs"]
    verbs: ["get","list","watch"]