apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
        - env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: 'false'
            - name: xpack.security.http.ssl.enabled
              value: 'false'
            - name: ES_JAVA_OPTS
              value: '-Xms512m -Xmx512m'
          image: docker.elastic.co/elasticsearch/elasticsearch:8.2.1
          name: elasticsearch
          ports:
            - containerPort: 9200
              name: elastic-http
          resources:
            limits:
              memory: 20Mi
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
      volumes:
        - emptyDir: {}
          name: es-data

---
apiVersion: apps/v1
kind: Service
metadata:
  name: elastic-service
  namespace: logging
spec:
  ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
  selector:
    component: elasticsearch
  type: LoadBalancer
