apiVersion: apps/v1
kind: DeamonSet
metadata:
  name: fluentd
  namespace: logging
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      containers:
        - env:
            - name: K8S_NODE_NAME
              value: docker-cluster
            - name: FLUENT_ELASTICSEARCH_HOST
              value: elasticsearch
            - name: FLUENT_ELASTICSEARCH_PORT
              value: '9200'
            - name: FLUENTD_SYSTEMD_CONF
              value: disable
          image: fluent/fluentd-kubernetes-deamonset:v1.16-debian-elasticsearch8-2
          name: fluentd
          volumeMounts:
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
      serviceAccountName: fluentd
      volumes:
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
        - name: config-volume
